PATH = File.expand_path "../", __FILE__

# RUN_ID = "00000-images_tf-mirror-stylegan2-gamma10-kimg1000-ada-bgc"
RUN_ID = "00002-images_tf-mirror-stylegan2-gamma10-kimg1000-ada-bgc"

DEFAULT_IP = nil
# DEFAULT_IP = "207.53.234.253"

USER = "ubuntu"
# USER = "user"

vm_ip = unless DEFAULT_IP
  ip = File.read File.expand_path "#{PATH}/../infra/outputs/vm_1_public_ip.txt"
  ip.strip
else
  DEFAULT_IP
end

VM_IP = vm_ip
puts "VM_IP: #{VM_IP}"

desc "Configure the ML env inside nvidia-docker"
task :configure do
  sh "ruby lib/ml_env_configure.rb"
end

desc "ssh into the machine"
task :ssh do
  sh "ssh #{USER}@#{vm_ip}"
end

desc "Download data to local machine"
task :download do
  sh "scp -r #{USER}@#{VM_IP}:/home/#{USER}/data/output ../data/output/"
end

desc "Download data to local machine - fakes images only"
task :download_fakes do
  sh "scp -r #{USER}@#{VM_IP}:/home/#{USER}/data/output/**/*.png ../data/output/"
end

desc "Download data to local machine - latest model only"
task :download_model do
  dir_run = "/home/#{USER}/data/output/#{RUN_ID}"
  model_file = `ssh #{USER}@#{VM_IP} ls -t #{dir_run}/*.pkl | head -1`
  model_file.strip!
  puts "executing: #{model_file}"
  sh "scp -r #{USER}@#{VM_IP}:#{model_file} ../data/output/"
end


desc "Download data to local machine - latest fake only"
task :download_fake do
  dir_run = "/home/#{USER}/data/output/#{RUN_ID}"
  model_file = `ssh #{USER}@#{VM_IP} ls -t #{dir_run}/*.png | head -1`
  model_file.strip!
  puts "executing: #{model_file}"
  sh "scp -r #{USER}@#{VM_IP}:#{model_file} ../data/output/"
end

desc "Download data to local machine - fakes images only"
task :download_run_fakes do
  sh "scp -r #{USER}@#{VM_IP}:/home/#{USER}/data/output/#{RUN_ID}r /*.png ../data/output/"
end

desc "Nvidia Stats"
task :stats do
  sh "ssh #{USER}@#{VM_IP} nvidia-smi"
end

desc "Logs"
task :logs do
  sh "ssh #{USER}@#{VM_IP} sudo docker logs -f $(ssh #{USER}@#{VM_IP} sudo docker ps | grep stylegan2 | cut -d \" \" -f1) 2>&1"
end

desc "List - Look at the data directory content"
task :list do
  dir_out = "/home/#{USER}/data/output"
  sh "ssh #{USER}@#{VM_IP} ls #{dir_out}"
end

task dl:  :download
task log: :logs
task ls:  :list

task default: :configure
