PATH = File.expand_path "../", __FILE__

vm_ip = File.read "#{PATH}/../infra/outputs/vm_1_public_ip.txt"
vm_ip.strip!
VM_IP = vm_ip

USER = "ubuntu"

desc "Configure the ML env inside nvidia-docker"
task :configure do
  sh "ruby lib/ml_env_configure.rb"
end

desc "ssh into the machine"
task :ssh do
  sh "ssh ubuntu@#{vm_ip}"
end

desc "Download data to local machine"
task :download do
  sh "scp -r #{USER}@#{VM_IP}:/home/#{USER}/data/output ../data/output"
end

RUN_ID = "00002-images_tf-stylegan2-gamma4-kimg1000-ada-bgc"

desc "Download data to local machine - fakes images only"
task :download_fakes do
  sh "scp -r #{USER}@#{VM_IP}:/home/#{USER}/data/output/#{RUN_ID}/*.png ../data/output"
end

desc "Download data to local machine - latest model only"
task :download_model do
  dir_run = "/home/#{USER}/data/output/#{RUN_ID}"
  model_file = `ssh #{USER}@#{VM_IP} ls -t #{dir_run}/*.pkl | head -1`
  model_file.strip!
  puts "executing: #{model_file}"
  sh "scp -r #{USER}@#{VM_IP}:#{model_file} ../data/output"
end

task dl: :download

task default: :configure
