PATH = File.expand_path "../", __FILE__

vm_ip = File.read "#{PATH}/../infra/outputs/vm_1_public_ip.txt"
vm_ip.strip!
VM_IP = vm_ip

USER = "ubuntu"

desc "Configure the ML env inside nvidia-docker"
task :configure do
  sh "ruby lib/ml_env_configure.rb"
end

desc "ssh into the machine"
task :ssh do
  sh "ssh ubuntu@#{vm_ip}"
end

desc "Download data to local machine"
task :download do
  sh "scp -r #{USER}@#{VM_IP}:/home/#{USER}/data/output ../data/output"
end

RUN_ID = "00000-images_tf-stylegan2-gamma10-kimg3000-ada-bgc"

desc "Download data to local machine - fakes images only"
task :download_fakes do
  sh "scp -r #{USER}@#{VM_IP}:/home/#{USER}/data/output/**/*.png ../data/output"
end

desc "Download data to local machine - latest model only"
task :download_model do
  dir_run = "/home/#{USER}/data/output/#{RUN_ID}"
  model_file = `ssh #{USER}@#{VM_IP} ls -t #{dir_run}/*.pkl | head -1`
  model_file.strip!
  puts "executing: #{model_file}"
  sh "scp -r #{USER}@#{VM_IP}:#{model_file} ../data/output"
end

desc "Logs"
task :logs do
  sh "ssh #{USER}@#{VM_IP} docker logs -f $(ssh #{USER}@#{VM_IP} docker ps | grep stylegan2 | cut -d \" \" -f1) 2>&1"
end

desc "List - Look at the data directory content"
task :list do
  dir_out = "/home/#{USER}/data/output"
  sh "ssh #{USER}@#{VM_IP} ls #{dir_out}"
end

task dl:  :download
task log: :logs
task ls:  :list

task default: :configure
